Added tutorial for Squid
canonical-web-and-design/tutorials.ubuntu.com pull request #561
Opened 2017-12-15 06:01 UTC by Tanesh1701

Added tutorial for Squid

2017-12-15 06:01 UTC, webteam-app commented
User is not a collaborator of this repo. Please start demo manually.

2019-03-17 16:12 UTC, pmahnke requested changes
Many recomendations for typos and spelling.  Also, can you rename this file to squid-proxy.md ?

Thanks, looking really good so far.

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> + In this tutorial,we will be installing and configuring a caching proxy-Squid,which is one of the best proxies out there.
```suggestion
 In this tutorial, we will be installing and configuring a caching proxy-Squid, which is one of the best proxies out there.
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +  For the first step,we will be installing Squid using the Terminal.Without further ado,lets type in the command
```suggestion
  For the first step, we will be installing Squid using the Terminal. Without further ado, lets type in the command:
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +  Now that we have already installed Squid,we will be configuring it.The configuration of the Squid Proxy Server is handled in the /etc/squid/squid.conf.(We can also check if Squid is running properl
```suggestion
  Now that we have already installed Squid, we will be configuring it. The configuration of the Squid Proxy Server is handled in the /etc/squid/squid.conf (we can also check if Squid is running properly by typing in the command-`sudo service squid status`).
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +  As such we can also change the TCP port that our Squid Server is using.To do this we type in the following command in the terminal:
```suggestion
  As such we can also change the TCP port that our Squid Server is using. To do this we type in the following command in the terminal:
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +                            `http_port ....`(ex:8888 instead of 3128(default one))
```suggestion
                            `http_port ....`(ex:8888 instead of 3128, the default)
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +                             for xample: `acl fortytwo_network src 192.168.42.0/24`
```suggestion
                             for example: `acl fortytwo_network src 192.168.42.0/24`
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +  Then add the following command to the top of the acl of/etc/squid/squid.conf
```suggestion
  Then add the following command to the top of the acl of `/etc/squid/squid.conf`
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +Now that we have configured Squid,we must now restart it to apply the changes to it.
```suggestion
Now that we have configured Squid, we must now restart it to apply the changes to it.
```

2019-03-17 16:12 UTC, pmahnke commented on tutorials/server/Proxy.md
> +## And thats all folks....Feel free to explore the other commands
```suggestion
## And thats all folks... Feel free to explore the other commands.
```

2020-02-10 14:24 UTC, steverydz commented
Thanks for submitting a pull request for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/c/tutorials

2020-02-10 14:24 UTC, closed without merging