Update create first snap
canonical-web-and-design/tutorials.ubuntu.com pull request #922
Opened 2019-02-08 10:17 UTC by popey

Update first snap creation tutorial to use multipass / bases and better best practices.

2019-02-08 10:17 UTC, webteam-app commented
User is not a collaborator of this repo. Please start demo manually.

2019-02-14 10:07 UTC, degville commented
@popey same for this one:
```
59 ![IMAGE](./hero-artwork.png)
```

2019-05-21 13:33 UTC, cjp256 requested changes
I think these updates are important so newcomers like myself don't stumble in the introduction :D

The second commit `Update basic snap usage` removes the hero-artwork.png from basic-snap-usage tutorial.  That commit probably wasn't intentional and should be removed (as it is still referenced in that tutorial).

2019-05-21 13:37 UTC, cjp256 commented on tutorials/packaging/create-your-first-snap/create-your-first-snap.md
> +Next we will install multipass to manage the Virtual Machines in which snapcraft will build.
I don't think this section is required anymore.  It looks like multipass is shipping with the latest stable snapcraft.

2019-05-21 13:44 UTC, cjp256 commented on tutorials/packaging/create-your-first-snap/create-your-first-snap.md
> +sudo apt install hello
NIT: trailing whitespace

2019-05-21 14:18 UTC, cjp256 commented on tutorials/packaging/create-your-first-snap/create-your-first-snap.md
> +snapcraft clean gnu-bash
Testing this, I did not get the error described here.  Maybe there is a change which eliminates this error and we can simply remove this section (and perhaps find a new example for configflags).  Removing the section will also address the follow-up usage of `snapcraft prime`

2019-05-21 14:23 UTC, cjp256 commented
I tested these changes locally after dropping the commit which removes hero-artwork.png, and everything appeared to render correctly.

2019-05-21 14:27 UTC, cjp256 commented
FWIW, the easiest way to get this running locally in my experience, just simply exec:
```
./run serve tutorials
```

2020-02-10 15:48 UTC, steverydz commented
Thanks for submitting a PR for this tutorial. We have moved our tutorials to discourse. To contribute going forwards please go to https://discourse.ubuntu.com/t/create-your-first-snap/14006/2

2020-02-10 15:48 UTC, closed without merging